services:
  # API Service
  - type: web
    name: cost-manager-api
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000
    healthCheckPath: /api/about
    autoDeploy: true

# Configuration Notes:
# 1. Create a free account at render.com
# 2. Connect your GitHub repository
# 3. Add your MongoDB URI in the Environment Variables section
# 4. Deploy will happen automatically when you push to main/master branch
